project:
  type: book
  output-dir: docs
book:
  title: "Stats"
  reader-mode: true
  cover-image: Kolokotronis01.jpg
  favicon: Kolokotronis01.jpg
  
  chapters:
    - index.qmd
    #- intro.qmd
    #- summary.qmd
    #- references.qmd
    
    - part: chapter1.qmd
      chapters: 
        - combinations.qmd

bibliography: references.bib

format:
  html:
    theme: default
  pdf:
    documentclass: scrreprt



