project:
  type: book
  output-dir: docs
book:
  title: "Μανιφέστο"
  author: "Θεώδορος Κολοκοτρώνης"
  date: "03/25/1821"
  chapters:
    - index.qmd
    - chapter1.qmd
    #- intro.qmd
    #- summary.qmd
    #- references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



